# Generated by Django 3.2.12 on 2024-06-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.AlterField(
            model_name='collectionuser',
            name='groups',
            field=models.ManyToManyField(null=True, related_name='collection_users', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='collectionuser',
            name='user_permissions',
            field=models.ManyToManyField(null=True, related_name='collection_users', to='auth.Permission'),
        ),
    ]
