# Generated by Django 5.0.1 on 2024-04-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='background',
            field=models.ImageField(null=True, upload_to='content'),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='content'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='content'),
        ),
    ]
