# Generated by Django 5.0.1 on 2024-04-26 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0002_alter_classes_background_alter_student_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='religion',
        ),
        migrations.AddField(
            model_name='student',
            name='registrationDate',
            field=models.DateField(max_length=100, null=True),
        ),
    ]
