# Generated by Django 5.0.1 on 2024-04-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0004_banner_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
