# Generated by Django 3.2.12 on 2024-06-12 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0005_alter_attendance_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='classes',
        ),
    ]
