# Generated by Django 3.2.12 on 2024-06-16 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0008_student_classes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='course',
        ),
        migrations.RemoveField(
            model_name='student',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='student',
            name='group',
        ),
        migrations.DeleteModel(
            name='Classroom',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
