# Generated by Django 3.2.12 on 2024-06-17 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0009_auto_20240616_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='registrationDate',
        ),
    ]
